### ISSUE TITLE
[BUG] - Risk of Rain 2- failed to export code with reason code 400

### ISSUE THREAD

**Issue by Drooskie** [ebkr/r2modmanPlus#1040]
**Describe the bug**
After installing mods through R2 modman I went to export the code and it failed and I was given reason code 400. I attempted to do the same thing on a separate computer and was met with the same problem however the process used is the same process I've always used to install mods and then export. I did Run the game modded so that all the configuration files were updated and then went through and changed the configs to my preferences without messing with any of the options that said not to change.

**To Reproduce**
1. Install appropriate mods
2. Run game as modded
3. Restart mod manager and update configuration files
4. Run game as modded to make sure mods work
5. Go back into mod manager and click on export profile as code

**Expected behavior**
Expect to have code copied to clipboard to be shared.

**Screenshots**
![16870304825645897780209792293273](https://github.com/ebkr/r2modmanPlus/assets/136928703/1e3763df-4fd7-4101-a1ab-d08ac8601e1e)

**Comment by Hypertoken** [comment]
Different game (Valheim) same issue.

**Comment by bennysp** [comment]
+1 (Valheim)

**Comment by ebkr** [comment]
This should be resolved now

**Comment by Zeinath** [comment]
> This should be resolved now

Using version 3.1.42, trying to import via both code and file on Valheim, issue still persisting. Is this not the latest version?

**Comment by ebkr** [comment]
These errors are either due to outages or profiles being too large (which I believe is reported back as an error now). Please respond if you still have any problems with this, otherwise I'll close the issue.
