### ISSUE TITLE
[BUG] - Failed Code Export

### ISSUE THREAD

**Issue by UnrealisticTimeJump** [ebkr/r2modmanPlus#1160]
**Describe the bug**

**To Reproduce**
1. Go to 'settings'
2. Click on 'export profile as code'
3. See error 504

**Expected behavior**
Gives profile code to share.
**Screenshots**
![504](https://github.com/ebkr/r2modmanPlus/assets/154753176/fccf1ecc-2051-4c05-8251-4b9e5d71a9e1)

**Additional context**

**Comment by UnrealisticTimeJump** [comment]
Issue has been fixed

**Comment by abarbato** [comment]
this issue is not fixed, i had trouble exporting earlier this evening but now i can export the code, i gave to a few friends for lethal company to import the mod list and we all get that error.

**Comment by LocoThea** [comment]
so do i

**Comment by arturallmann** [comment]
[https://github.com/ebkr/r2modmanPlus/issues/636#issuecomment-934587004](older thread with the same problem)

**Comment by MJHeijster** [comment]
> [#636 (comment)](https://github.com/ebkr/r2modmanPlus/issues/636#issuecomment-934587004)

Nope, that's not it. Profiles that were exportable yesterday are not working at the moment.

**Comment by MythicManiac** [comment]
The sharing feature was temporarily disabled over the weekend, the best place to receive announcements for updates like this currently is the Thunderstore Discord server here: https://discord.thunderstore.io/
