### ISSUE TITLE
[BUG] - Cant export profile as a code

### ISSUE THREAD

**Issue by YuroKashine** [ebkr/r2modmanPlus#1161]
**Describe the bug**
The moment i try to export my lethal company profile as a code it gives me an error about not able to read properties of undefined (reading 'key') and i have no clue what that might be.

**To Reproduce**
1. Go to 'settings'
2. Click on 'export profile as a code'
3. See error below

**Expected behavior**
Ofcourse i expect thunderstore to make a code like usual that i can give to my friends to play together.

**Screenshots**
![image](https://github.com/ebkr/r2modmanPlus/assets/156379068/e82846e7-86c5-4fe9-ab94-caad515f3d99)

**Additional context**
Im doing configurations in the mod config files. just the settings, nothing with codes and such. i do what i always do in the configs and exporting as a code always worked untill 30 minutes ago and i even removed the configs i made to reset them and it still didnt work.

**Comment by YuroKashine** [comment]
Looks like its fixed now!

**Comment by spookybjorn** [comment]
Unfortunately this issue is still not fixed, I and 5 other friends are currently having issues exporting profiles as code. we all get varying errors of 502, 503, and 504

**Comment by LocoThea** [comment]
so do i

**Comment by YuroKashine** [comment]
Yeah the error is back for me as well

**Comment by codakairos** [comment]
same

**Comment by codakairos** [comment]
This seems to be a problem with the thunderstore API (`https://thunderstore.io/api/experimental/legacyprofile/create`)

**Comment by YuroKashine** [comment]
@codakairos so did u find a way to fix it?

**Comment by codakairos** [comment]
No, I'll just use export as file instead, we'll have to wait for thunderstorm to update their api, or for r2modman to find an alternative

**Comment by Ruikio** [comment]
Will throw my hat in here.

Happened with me as well. In my case I had just installed the Lethal Company VR mod so I thought it was that. Seems it may just be R2Modman.

**Comment by codakairos** [comment]
As explained in the Thunderstore discord, the issue was on the API side of thunderstore and should be fixed now.
![image](https://github.com/ebkr/r2modmanPlus/assets/112564682/494e5880-68cb-4581-884f-716b5820f628)

I think we can mark this issue as resolved or at least as "won't fix" as it is not directly related to r2modman

**Comment by codakairos** [comment]
For context, this error message was triggered here
https://github.com/ebkr/r2modmanPlus/blob/01bf512fef0026746275fdeddc6cdb49b164402b/src/r2mm/profiles/ProfilesClient.ts#L9
while trying to reach the Thunderstore API endpoint `https://thunderstore.io/api/experimental/legacyprofile`
(also happened while trying to retrieve a profile from the same endpoint)

**Comment by astranberg** [comment]
I am having this issue as well. However, my r2modman appears to have a memory leak when trying to export as code. It eats upwards of 4GB of memory while doing this. Sometimes application itself becomes unresponsive.

**Comment by ebkr** [comment]
As this was related to the Thunderstore API, I'll close this for now.
