### ISSUE TITLE
[BUG] - r2modman cannot launch modded Valheim following the latest Steam update on Linux

### ISSUE THREAD

**Issue by Crushnaut** [ebkr/r2modmanPlus#1534]
**Describe the bug**
Steam pushed out an update which added screen recording for all platforms. This update also included an update to the runtime environment for native games. By default steam now uses something called scout 1.0. Here are the relevant patch notes: https://store.steampowered.com/news/app/593110/view/4472730495692571024

"Native titles will execute in 'Steam for Linux runtime 1.0 (scout)' by default, instead of the legacy runtime environment."

This seems to have broken r2modman's ability to launch valheim in modded mod. The game can still be launched in vanilla mode.

**To Reproduce**
1. Create a valheim modded profile on r2modman
2. Try to launch valheim
3. Steam will open and valheim will briefly show it is running and then immediately crash
4. You should be able to launch valheim in vanilla mode via steam directly or via r2modman

**Expected behavior**
Valheim should launch with mods

**Screenshots**
NA

**Additional context**
I have a work around for this issue. You can add the launch parameter "-compat-force-slr off" to the r2modman steam launch parameters. I documented this solution in the discord (https://discord.com/channels/727304496522461185/1303809239898259476/1303909649153527870) and here: https://www.reddit.com/r/valheim/comments/1glggwy/workaround_modded_valheim_on_linux_with_r2modman/

A handful of people have verified that this work around works. 

Confirmed an issue on Arch, Kubuntu, and Pop!

This launch parameter forces steam to use the legacy runtime environment from before the update.

Other have stated that they manually installed the mods and launched valheim via Steam in the new runtime environment and it works without issue.

This was an issue in r2modman 51 and 52.

I have also tried creating a fresh profile and updating mods to the latest which did not fix the issue. I also tried making a barebones profile with just a couple simple mods and this also did not launch.

When you launch Valheim in vanilla mode valheim also talks about not being about to load PlayFab and requiring some MS runtime files. Unsure if this is related.

**Comment by archiebug** [comment]
I can confirm.  I manually load BepInEx.  Since the latest Steam update, Valheim no longer loads.  When i Start team using "-compat-force-slr off", Valheim, with BepInEx loads fine.  I'm also able to just start Valheim outside of Steam just using the sh script.

**Comment by oDD-1** [comment]
I have this problem on Arch (EndeavourOS), but the workaround does not work for me. Valheim quits on the title screen.

**Comment by cethien** [comment]
workaround for now:
in steam properties for Valheim, select "Legacy runtime 1.0"

![image](https://github.com/user-attachments/assets/f4ce4062-f46d-4576-b0d8-e4c36bfa3e8d)

i have ValheimPlus with BepInEx and works fne

(i use NixOS btw)

**Comment by M15071060** [comment]
To add to this discussion, for what it's worth, I was able to get this functioning on my system (Debian Bookworm - 6.1.0-21-amd64 using r2modman) by solely modifying the `start_game_bepinex.sh` file.

I modified

``` 
# exec="$BASEDIR/valheim.x86_64"
 exec="/media/m15071060/ext4 partition/SteamLibrary/steamapps/common/Valheim/valheim.x86_64"
```

and 

```
# Run the main executable
# Don't quote here since $exec may contain args passed by Steam
# if [ -n "$launch" ]; then
#     exec "$launch" $rest
# else
    echo "Executing standard version"
    exec "$exec"
# fi
```

Adjusted file: [start_game_bepinex.txt](https://github.com/user-attachments/files/18104648/start_game_bepinex.txt)




So it just executes the "correct" path. If I don't do this, the launch breaks because of a space in the filename `/media/m15071060/ext4 partition/SteamLibrary/steamapps/common/Valheim/valheim.x86_64` with this error: `scout-legacy: 5: exec: /media/m15071060/ext4: not found`

I don't see where or why the path would break otherwise, but this allows me to launch modded without Steam open in any alternative modes, nor selecting a specific runtime. It does fail to launch from Steam because of the launch options, however, so that's a definite caveat.

**Comment by Coltrain47** [comment]
I'm having the same problem on Steam Deck. The "-compat-force-slr off" workaround only sort of works for me. I can get the game to start modded, but the quality is terrible no matter what settings I use (and I only have a couple light mods that shouldn't affect frame rate). 

Not to mention, having to completely shut down Steam every time I want to play Valheim on a Steam Deck is quite the hassle. I also don't have the ability to force the use of the legacy runtime in the game's properties like cethien has done.

**Comment by archiebug** [comment]
A fix in the steam client might have fixed this issue:  https://github.com/ValveSoftware/steam-for-linux/issues/11448
However, running the latest beta and not messing with compatibility still doesn't let the game start with calling the .sh file within the Steam client. 

I also have "Legacy runtime 1.0" available in the drop down in the Compatibility settings.  That seems to have fixed things.  I believe the correct thing to do is to get the startup script fixed that @M15071060 mentions.  Valheim runs fine without using bepinex.

**Comment by Crushnaut** [comment]
@ebkr could this fix be integrated into r2modman? or is this a problem with Bepinex? if the later, how can we pass this along to them?

**Comment by HarlemSquirrel** [comment]
Looks like this is a problem with bepinex. See https://github.com/BepInEx/BepInEx/issues/1032

**Comment by Kovakin** [comment]
With the fix provided by [M15071060](https://github.com/M15071060), I am able to get Valheim to open to the loading screen but I get a near immediate crash with the terminal reporting as follows:

`ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

I am running CachyOS on Kernel Linux 6.13.5-arch1-1 with DE KDE Plasma 6.3.2 on Wayland
CPU: AMD Ryzen 5 3600X
GPU: AMD Radeon RX 6700 XT
Valheim is loaded onto a secondary drive from the main, located at `/run/media/kova/Main HDD/`

I attempted to also implement the fix this using the solution provided here by [eliadevito](https://github.com/eliadevito) and on the [BepInEx/BepInEx#1032](https://github.com/BepInEx/BepInEx/issues/1032) issue, but both solutions have failed with the same error.

**Comment by illspirit** [comment]
I'm having the same issue as @Kovakin - it will load intermittently. The solution by @eliadevito  did not work - the game will load but not with bepinex loaded

**Comment by eliadevito** [comment]
@Kovakin @illspirit  This is my start_game_bepinex.sh that I'm using without any problems, can you verify if you applied the changes in the same way and eventually send the complete file?
```

#!/bin/sh
# BepInEx running script
#
# HOW TO USE:
# 1. Make this script executable with `chmod u+x ./start_game_bepinex.sh`
# 2. In Steam, go to game's preferences and change game's launch args to:
#    ./start_game_bepinex.sh %command%
# 3. Start the game via Steam
#
# Note that you won't get a console this way
#
# NOTE: Edit the script only if you know what you're doing!

# Resolve base directory relative to this script
# Hopefully this resolves relative paths and links
a="/$0"; a=${a%/*}; a=${a#/}; a=${a:-.}; BASEDIR=$(cd "$a"; pwd -P)

# Special case: program is launched via Steam
# In that case rerun the script via their bootstrapper to ensure Steam overlay works
if [ "$2" = "SteamLaunch" ]; then
    cmd="$1 $2 $3 $4 $0"
    shift 4
    exec $cmd $@
    exit
fi

# Special case: program is launched via Steam through steam-launch-wrapper
# In that case rerun the script via their bootstrapper to ensure game start correctly
if [[ $1 == *"steam-launch-wrapper"* ]]; then
  	cmd="$1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} $0"
	shift 11
	exec $cmd $@
	exit
fi

exec="$BASEDIR/valheim.x86_64"

export DOORSTOP_ENABLE=TRUE
export DOORSTOP_INVOKE_DLL_PATH="$BASEDIR/BepInEx/core/BepInEx.Preloader.dll"
export DOORSTOP_CORLIB_OVERRIDE_PATH="$BASEDIR/unstripped_corlib"

# Allow to specify --doorstop-enable true|false
# Everything else is passed as-is to `exec`
while :; do
    case $1 in
        --doorstop-enable)
            if [ -n "$2" ]; then
                export DOORSTOP_ENABLE=$(echo "$2" | tr a-z A-Z)
                shift
            else
                echo "No --doorstop-enable value specified, using default!"
            fi
            ;;
        --doorstop-target)
            if [ -n "$2" ]; then
                export DOORSTOP_INVOKE_DLL_PATH="$2"
                shift
            else
                echo "No --doorstop-target value specified, using default!"
            fi
            ;;
        --doorstop-dll-search-override)
            if [ -n "$2" ]; then
                export DOORSTOP_CORLIB_OVERRIDE_PATH="$2"
                shift
            else
                echo "No --doorstop-dll-search-override value specified, using default!"
            fi
            ;;
        *)
            if [ -z "$1" ]; then
                break
            fi
            if [ -z "$launch" ]; then
                launch="$1"
            else
                rest="$rest $1"
            fi
            ;;
    esac
    shift
done


export LD_LIBRARY_PATH="$BASEDIR/doorstop_libs:$LD_LIBRARY_PATH"
export LD_PRELOAD="libdoorstop_x64.so:$LD_PRELOAD"


# Run the main executable
# Don't quote here since $exec may contain args passed by Steam
if [ -n "$launch" ]; then
    exec "$launch" $rest
else
    exec "$exec"
fi
```

**Comment by illspirit** [comment]
> [@Kovakin](https://github.com/Kovakin) [@illspirit](https://github.com/illspirit) This is my start_game_bepinex.sh that I'm using without any problems, can you verify if you applied the changes in the same way and eventually send the complete file?
> 
> ```
> 
> #!/bin/sh
> # BepInEx running script
> #
> # HOW TO USE:
> # 1. Make this script executable with `chmod u+x ./start_game_bepinex.sh`
> # 2. In Steam, go to game's preferences and change game's launch args to:
> #    ./start_game_bepinex.sh %command%
> # 3. Start the game via Steam
> #
> # Note that you won't get a console this way
> #
> # NOTE: Edit the script only if you know what you're doing!
> 
> # Resolve base directory relative to this script
> # Hopefully this resolves relative paths and links
> a="/$0"; a=${a%/*}; a=${a#/}; a=${a:-.}; BASEDIR=$(cd "$a"; pwd -P)
> 
> # Special case: program is launched via Steam
> # In that case rerun the script via their bootstrapper to ensure Steam overlay works
> if [ "$2" = "SteamLaunch" ]; then
>     cmd="$1 $2 $3 $4 $0"
>     shift 4
>     exec $cmd $@
>     exit
> fi
> 
> # Special case: program is launched via Steam through steam-launch-wrapper
> # In that case rerun the script via their bootstrapper to ensure game start correctly
> if [[ $1 == *"steam-launch-wrapper"* ]]; then
>   	cmd="$1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} $0"
> 	shift 11
> 	exec $cmd $@
> 	exit
> fi
> 
> exec="$BASEDIR/valheim.x86_64"
> 
> export DOORSTOP_ENABLE=TRUE
> export DOORSTOP_INVOKE_DLL_PATH="$BASEDIR/BepInEx/core/BepInEx.Preloader.dll"
> export DOORSTOP_CORLIB_OVERRIDE_PATH="$BASEDIR/unstripped_corlib"
> 
> # Allow to specify --doorstop-enable true|false
> # Everything else is passed as-is to `exec`
> while :; do
>     case $1 in
>         --doorstop-enable)
>             if [ -n "$2" ]; then
>                 export DOORSTOP_ENABLE=$(echo "$2" | tr a-z A-Z)
>                 shift
>             else
>                 echo "No --doorstop-enable value specified, using default!"
>             fi
>             ;;
>         --doorstop-target)
>             if [ -n "$2" ]; then
>                 export DOORSTOP_INVOKE_DLL_PATH="$2"
>                 shift
>             else
>                 echo "No --doorstop-target value specified, using default!"
>             fi
>             ;;
>         --doorstop-dll-search-override)
>             if [ -n "$2" ]; then
>                 export DOORSTOP_CORLIB_OVERRIDE_PATH="$2"
>                 shift
>             else
>                 echo "No --doorstop-dll-search-override value specified, using default!"
>             fi
>             ;;
>         *)
>             if [ -z "$1" ]; then
>                 break
>             fi
>             if [ -z "$launch" ]; then
>                 launch="$1"
>             else
>                 rest="$rest $1"
>             fi
>             ;;
>     esac
>     shift
> done
> 
> 
> export LD_LIBRARY_PATH="$BASEDIR/doorstop_libs:$LD_LIBRARY_PATH"
> export LD_PRELOAD="libdoorstop_x64.so:$LD_PRELOAD"
> 
> 
> # Run the main executable
> # Don't quote here since $exec may contain args passed by Steam
> if [ -n "$launch" ]; then
>     exec "$launch" $rest
> else
>     exec "$exec"
> fi
> ```

I used your start_game_bepinex.sh and when I hit Start Modded it loads up instantly but without Bepinex

**Comment by illspirit** [comment]
@eliadevito What complete file can I send?

**Comment by khionu** [comment]
@eliadevito [said](https://github.com/ebkr/r2modmanPlus/issues/1534#issuecomment-2544041339):
> This is caused by a change in the way steam launch game that broke start_game_bepinex.sh.
> 
> Adding this lines between line 25-27 of your start_game_bepinex.sh should solve the problem:
> [...]

This seems to be the most correct fix, imo. If this could get a maintainer's review and blessing, I'd be happy to make the PR

**Comment by arrowmaster** [comment]
I posted a better fix in https://github.com/BepInEx/BepInEx/issues/1032#issuecomment-2927833286, but we need an updated release of BepInEx for Valheim to be released with fixes included. I haven't been able to locate a repo where the start_game_bepinex.sh comes from to make a PR.

**Comment by Kengetsu** [comment]
> I posted a better fix in [BepInEx/BepInEx#1032 (comment)](https://github.com/BepInEx/BepInEx/issues/1032#issuecomment-2927833286), but we need an updated release of BepInEx for Valheim to be released with fixes included. I haven't been able to locate a repo where the start_game_bepinex.sh comes from to make a PR.

Not sure what i'm doing wrong here but this still doesn't work for me. Using r2modman manager with a fresh install of Valheim but starting the game just results in an immediate crash.  (basically steam play button goes to stop then back to play again) doesn't matter if I pick vanilla or modded from r2modman. 

OS: Fedora 42
DE: KDE Plasma
Steam: RPM install

**Comment by arrowmaster** [comment]
> Not sure what i'm doing wrong here but this still doesn't work for me. Using r2modman manager with a fresh install of Valheim but starting the game just results in an immediate crash. (basically steam play button goes to stop then back to play again) doesn't matter if I pick vanilla or modded from r2modman.

If you have set set the launch command inside Steam to `"/home/$HOME/.config/r2modmanPlus-local/Valheim/linux_wrapper.sh" %command%` then the start_game_bepinex.sh script is only executed when you use start modded from r2. I just tested this for confirmation and both launching from Steam and start vanilla in r2 skip start_game_bepinex.sh so something else is probably wrong.

Try setting the launch command to `logsave "$HOME/valheim.log" "/home/$HOME/.config/r2modmanPlus-local/Valheim/linux_wrapper.sh" %command%` and you will get a log of all the console output saved to $HOME/valheim.log to help in debugging.

**Comment by Kengetsu** [comment]
> > Not sure what i'm doing wrong here but this still doesn't work for me. Using r2modman manager with a fresh install of Valheim but starting the game just results in an immediate crash. (basically steam play button goes to stop then back to play again) doesn't matter if I pick vanilla or modded from r2modman.
> 
> If you have set set the launch command inside Steam to `"/home/$HOME/.config/r2modmanPlus-local/Valheim/linux_wrapper.sh" %command%` then the start_game_bepinex.sh script is only executed when you use start modded from r2. I just tested this for confirmation and both launching from Steam and start vanilla in r2 skip start_game_bepinex.sh so something else is probably wrong.
> 
> Try setting the launch command to `logsave "$HOME/valheim.log" "/home/$HOME/.config/r2modmanPlus-local/Valheim/linux_wrapper.sh" %command%` and you will get a log of all the console output saved to $HOME/valheim.log to help in debugging.

Ah ok, that's very helpful. Seems like it's not related to the bepinex script at all but the Steam/ubuntu12_32/gameoverlayrenderer.so library instead. Both modded and vanilla throw the same error when trying to start them. I did try to see if disabling the steam overlay setting did anything but it throws the same error. Just to note, that if I run the game without anything in the launch options it does indeed work fine so it's not anything with the game directly.

[valheim_vanilla.log](https://github.com/user-attachments/files/21026401/valheim_vanilla.log)

**Comment by arrowmaster** [comment]
> Ah ok, that's very helpful. Seems like it's not related to the bepinex script at all but the Steam/ubuntu12_32/gameoverlayrenderer.so library instead.

That is unrelated and you those errors in the console log on every game run though Steam.

Does the game launch if the launch options in Steam are blank? There's also an option to use OpenGL instead of the default Vulkan renderer. If you still cannot get the game to launch unmodded then its likely some system incompatibility that needs to be reported to the developer.

**Comment by Kengetsu** [comment]
> > Ah ok, that's very helpful. Seems like it's not related to the bepinex script at all but the Steam/ubuntu12_32/gameoverlayrenderer.so library instead.
> 
> That is unrelated and you those errors in the console log on every game run though Steam.
> 
> Does the game launch if the launch options in Steam are blank? There's also an option to use OpenGL instead of the default Vulkan renderer. If you still cannot get the game to launch unmodded then its likely some system incompatibility that needs to be reported to the developer.

Yeah that's the odd thing. Game runs perfectly fine with the launch options blank. It's only when using the r2modman launch options does it crash immediately. I even tried with a blank profile without mods and get the same results.

**Comment by arrowmaster** [comment]
@Kengetsu Try the following version of start_game_bepinex.sh with the launch options set to `DEBUG=1 logsave "$HOME/valheim.log" "/home/$HOME/.config/r2modmanPlus-local/Valheim/linux_wrapper.sh" %command%` and post the log file for starting modded in r2.

https://gist.github.com/arrowmaster/8193d48571dacdc602e395ba9520bbaf

**Comment by Kengetsu** [comment]
Doesn't seem to have much else information in there. 

[valheim.log](https://github.com/user-attachments/files/21027629/valheim.log)

![Image](https://github.com/user-attachments/assets/a8284780-2c8c-4ad3-ac51-42a933a71871)

**Comment by arrowmaster** [comment]
@Kengetsu It doesn't seem like the updated start_game_bepinex.sh is being run from that output. The updated file should be placed at `/home/kengetsu/.config/r2modmanPlus-local/Valheim/profiles/Default/start_game_bepinex.sh`. And there should NOT be a `run_bepinex.sh` file in the same directory.

**Comment by Kengetsu** [comment]
> [@Kengetsu](https://github.com/Kengetsu) It doesn't seem like the updated start_game_bepinex.sh is being run from that output. The updated file should be placed at `/home/kengetsu/.config/r2modmanPlus-local/Valheim/profiles/Default/start_game_bepinex.sh`. And there should NOT be a `run_bepinex.sh` file in the same directory.

Ok, I cleaned the profile and tried again just to make sure there wasn't anything odd in there. It does seem like some debug statements are in there now but the result is the same.

![Image](https://github.com/user-attachments/assets/cfc951b5-002f-4a29-9f8e-e42fa286e612)

[valheim.log](https://github.com/user-attachments/files/21029630/valheim.log)


This is the game running without any launch params just to confirm it does work when not using any of the mod related stuff.

![Image](https://github.com/user-attachments/assets/97ad468e-8b33-4341-b83a-8598a57030f2)

**Comment by arrowmaster** [comment]
@Kengetsu I see the problem now. I should have seen it earlier but it wasn't as obvious until the new log with the additional debug statements.

Your Steam library is located at `/mnt/2TB 870 Evo/Steam` which includes spaces. Neither start_game_bepinex.sh or r2modmans linux_wrapper.sh will currently work properly with spaces in a path. I'm going to look more into how this can be fixed but its complicated and going to probably take some time.

**Comment by arrowmaster** [comment]
@Kengetsu I might have found a solution but its going to first need testing by you and then I'm going to need to find somebody that knows POSIX scripting better than me to confirm I'm not being a lunatic for doing it this way.

Try this special version but it also has special installation instructions. First you need to launch r2modman. After r2modman is running and you have Valheim selected and ready to launch, then you need to replace `~/.config/r2modmanPlus-local/Valheim/linux_wrapper.sh` with the new version. Unfortunately r2modman will replace this file on startup so this is only a temporary fix for testing (maybe you can change it to readonly, idk if that will work). If this works then both BepInEx and r2modman will need to merge in the changes.

https://gist.github.com/arrowmaster/e19ae5790033d6c71ab586ee782eeb8d

**Comment by Kengetsu** [comment]
> [@Kengetsu](https://github.com/Kengetsu) I might have found a solution but its going to first need testing by you and then I'm going to need to find somebody that knows POSIX scripting better than me to confirm I'm not being a lunatic for doing it this way.
> 
> Try this special version but it also has special installation instructions. First you need to launch r2modman. After r2modman is running and you have Valheim selected and ready to launch, then you need to replace `~/.config/r2modmanPlus-local/Valheim/linux_wrapper.sh` with the new version. Unfortunately r2modman will replace this file on startup so this is only a temporary fix for testing (maybe you can change it to readonly, idk if that will work). If this works then both BepInEx and r2modman will need to merge in the changes.
> 
> https://gist.github.com/arrowmaster/e19ae5790033d6c71ab586ee782eeb8d

AMAZING! That does allow the game to fully launch and it does seem like all the mods are working correctly. Thanks so much for all the help with this!

**Comment by arrowmaster** [comment]
> > [@Kengetsu](https://github.com/Kengetsu) I might have found a solution but its going to first need testing by you and then I'm going to need to find somebody that knows POSIX scripting better than me to confirm I'm not being a lunatic for doing it this way.
> > Try this special version but it also has special installation instructions. First you need to launch r2modman. After r2modman is running and you have Valheim selected and ready to launch, then you need to replace `~/.config/r2modmanPlus-local/Valheim/linux_wrapper.sh` with the new version. Unfortunately r2modman will replace this file on startup so this is only a temporary fix for testing (maybe you can change it to readonly, idk if that will work). If this works then both BepInEx and r2modman will need to merge in the changes.
> > https://gist.github.com/arrowmaster/e19ae5790033d6c71ab586ee782eeb8d
> 
> AMAZING! That does allow the game to fully launch and it does seem like all the mods are working correctly. Thanks so much for all the help with this!

Great! I've submitted a PR for r2modman's wrapper script. https://github.com/ebkr/r2modmanPlus/pull/1843

**Comment by itenev** [comment]
@arrowmaster just an fyi, the pull request is waiting on you to sign the contributor license

**Comment by arrowmaster** [comment]
> [@arrowmaster](https://github.com/arrowmaster) just an fyi, the pull request is waiting on you to sign the contributor license

Interesting, so it is. And I have to sign up with some third party site to do so.

I guess I'll just go cancel the pull request.

**Comment by arrowmaster** [comment]
denikson-BepInExPack_Valheim-5.4.2330 has been released on Thunderstore that should resolve the issues with Steam.

**Comment by Kahnshaak** [comment]
I am still having this issue. I just installed the game fresh, and downloaded the modman appimage fresh from the website. So I think it should have all the fixes in it.

I was trying to install a set of mods my friend was using off a code. But I also tried to make a separate profile with a single mod and its not launching. Valheim launches properly from Steam, and when I hit 'Start Vanilla' in modman, but not when I try to start modded.

I tried fixes mentioned further up like adding parameters mentioned like `--r2profile "PROFILE_NAME"`. I checked the config files and it looks like they match what people have posted. I am not sure why this isn't working.

I tried this on both wayland and x11 just to see and its acting the same on both. I am not sure if its just an issue for the distro I am using since I don't see anyone else in the chain using anything debian based.

[valheim.log](https://github.com/user-attachments/files/22454630/valheim.log)

<img width="314" height="187" alt="Image" src="https://github.com/user-attachments/assets/d10a61db-7d5d-450e-8062-3c7c61ca3ad2" />

**Comment by ebkr** [comment]
@Kahnshaak There currently seems to be an issue with the wrapper fetching which should be fixed in the next version.

**Comment by ThisIsRinesi** [comment]
Still having the same issue as @Kahnshaak

**Comment by victor-schumann** [comment]
It has been a long time but for whoever comes across this in the future and has the Steam Deck, this is what fixed it for me: 

1. Using the most recent R2 release, copy the AppImage to desktop
2. Start R2, create a new profile for Valheim, install basic mods (a simple that you know how to normally validate and that is low in complexity)
3. Start Valheim from R2 and after validating mods are working, close the game
4. Go to the help section of R2 and copy the arguments at the bottom of the page 
5. Go to steam, Valheim, and update the Command Line Arguments in the Launch Options
6. Still in Desktop Mode, start the game from steam and validate if mods are working
7. Lastly, go to Game Mode and start the game

I believe the key was creating a new profile and starting from Mod Manager before starting from Steam. I hope this helps!

**Comment by JamesNMartin** [comment]
Yup can confirm @victor-schumann solution worked for me. I am able to start in game mode with the mods.

**Comment by JordanW9232** [comment]
Wow I've been fighting with this for like 2 hours but @victor-schumann suggestion finally worked. Skål!
