### ISSUE TITLE
[BUG] - R2MM won't open on linux (tried using .deb and appimage on latest and second latest release)

### ISSUE THREAD

**Issue by FFFluoride** [ebkr/r2modmanPlus#978]
**Describe the bug**
I open r2modman, the window opens. After a couple seconds it closes again. when I ran it in the terminal, it gave the error message:

```
[10898:0223/000144.125829:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
```

**To Reproduce**
1. Install latest release
2. run it on linux (I'm using pop os specifically)
3. Running it in terminal gives you a small log. Running it using the launcher fails silently

**Expected behavior**
It runs r2modman

**Comment by LiamDroog** [comment]
Having the same issue on Ubuntu (22.04 jammy)
Appimage dies quietly with no log or output. Installing .deb and running from the CLI gives:

`starting server on  /tmp/app.r2mm 
starting TLS server false
starting server as Unix || Windows Socket
[243248:0222/195403.782001:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)`

**Comment by zackwhit** [comment]
From the appimage, try running it with the '--in-process-gpu' argument added in the command line. Worked for me to get it to start when I got the "GPU process isn't usable" error. @FFFluoride 

Ubuntu 22.04.

**Comment by FFFluoride** [comment]
> 

I tried it with the .deb package and it worked thanks.

**Comment by Shamamo** [comment]
I got the appimage to work with the `--no-sandbox` argument.

**Comment by BloodyIron** [comment]
> From the appimage, try running it with the '--in-process-gpu' argument added in the command line. Worked for me to get it to start when I got the "GPU process isn't usable" error. @FFFluoride
> 
> Ubuntu 22.04.

Same problem for me on 22.04, this launch flag worked for me for .deb version

**Comment by attemptedhippo** [comment]
> From the appimage, try running it with the '--in-process-gpu' argument added in the command line. Worked for me to get it to start when I got the "GPU process isn't usable" error. @FFFluoride
> 
> Ubuntu 22.04.

installed using the .pacman file on manjaro, this worked for me as well

**Comment by ebkr** [comment]
`--no-sandbox` (or `--in-process-gpu`) are required because an older version of Electron is used. Updating Electron would drop support for Windows 7.

**Comment by BloodyIron** [comment]
And how long is that expected to be that way for?

**Comment by BloodyIron** [comment]
So you would rather everyone have a worse experience just so that Windows 7 users need to be supported? Why not make it so that --in-process-gpu be on by default, and Windows 7 users need to run a flag to disable it, or something equivalent? I myself don't use Wayland, I use X11.

**Comment by ebkr** [comment]
> So you would rather non-Win7 users have a worse experience

Well, understandably I’d rather the larger user-base had the better experience. This isn’t reported too frequently and only affects a small portion of Linux users. 

So yes, I’m happy for this to remain an issue over dropping Windows 7 support.

I’m not sure how I could provide default commands to be applied to the appimage though.

**Comment by BloodyIron** [comment]
> > So you would rather non-Win7 users have a worse experience
> 
> Well, understandably I’d rather the larger user-base had the better experience. This isn’t reported too frequently and only affects a small portion of Linux users.
> 
> So yes, I’m happy for this to remain an issue over dropping Windows 7 support.
> 
> Obviously overall I’d rather all platforms had a good experience, but the focus is on where the users primarily are.
> 
> I’m not sure how I could provide default commands to be applied to the appimage though.

I'm not familiar with the best method either, but perhaps an inverse function is in-order whereby "in-process-gpu" is on-by-default, and the launch parameter be replaced with "--not-in-process-gpu" (or something equivalent) for when you want to disable that functionality.

The reason to me this is noteworthy is because as it stands running the application out of the box looks like it just 100% fails. There is zero feedback to the user if you just run it (not from a CLI) and naturally without the launch parameter. So it gives the user the impression that the software _just doesn't work at all_. Which will probably result in an immediate uninstall/deletion of the software. Users should not be expected to know about this launch parameter for baseline operations of the software.

Again, I'm not necessarily advocating for the dropping of support for any particular group (Win7 or otherwise), more that those that "need" this launch parameter are having such a bad UX that it's effectively a toxic experience. And I'm trying to say useful things that might help you... help us ;)

**Comment by neilunger** [comment]
I am also experiencing this issue. Using the .deb version of R2MM on Pop!_OS, I had to work around it by using superuser privileges to edit the line `Exec=/opt/r2modman/r2modman %U` to `Exec=/opt/r2modman/r2modman %U --no-sandbox` in `/usr/share/applications/r2modman.desktop`

@ebkr Since Windows 7 users are obviously fine using older software, why not just update Electron and then tell W7 users to download an older release of R2MM?

The Electron updates should have security, performance, and QoL updates that affect Windows 10 and 11 too, they don't just help linux. I'd expect the Electron/Chromium teams to have good reason for deciding to drop W7/8/8.1 support

**Comment by MartenBE** [comment]
I have this issue also on Fedora 39. W7 is end of life and a big security risk, we shouldn't encourage or endors it ... Forcing the update may even force them off W7 to a safer Windows version or other OS.

**Comment by gmes78** [comment]
Steam has recently dropped support for Windows 7/8/8.1, so it's probably fine to do so here as well if it's blocking issues like these.

**Comment by IAmTheRealGoof** [comment]
Following up. Linux Mint 21.2 running 6.5.0-26-generic kernel
Geforce 4060ti with nvidia-driver-535 535.161.07-0ubuntu0.22.04.1 showed this problem, both work arounds listed above worked independently,  (--no-sandbox or --in-process-gpu, though I do not know what they mean)  Same box running AMD 480 or AMD 6600 did not have this problem.

personally, I would like to see r2modman to work without requiring steam, since steam revoked win xp/7 games from playing.(not cracked, just not required to launch steam, but the game directly)

I mean I can manually mod the game and run games directly but one loses out from the niceties of a mod manager.

**Comment by sfjuocekr** [comment]
If you are on Wayland try:

GDK_BACKEND=x11 ./r2modman-3.1.50_f3cfa1fcc8651a86e0dd2ff7126ae2fb.AppImage --no-sandbox

**Comment by ebkr** [comment]
This should have been solved as part of #1519 

Since this hasn't had any further traction since, am I able to close this issue?

**Comment by calliereimann** [comment]
On a fresh install of the newest version of r2modman, 3.2.11, this bug is still present for the AppImage when using Debian.
